SQL setup scripts.

diff --git a/lib/bin/makedb-mysql b/lib/bin/makedb-mysql
--- a/lib/bin/makedb-mysql
+++ b/lib/bin/makedb-mysql
@@ -1,12 +1,8 @@
 #!/bin/bash
 DIR="$(dirname "$BASH_SOURCE")"
 . "$DIR/../bash/functions"
-echo -n 'working...'
+echo 'working...'
 {
-  # TODO appdir
-  cd "$DIR/../src/sql/mysql"
-} && {
-  echo
   confirm 'Do you really want to clobber the database?'
 } && {
   mysql -uroot -p <<SQL
@@ -20,4 +16,6 @@ SQL
   fi
 } && {
   echo 'done'
+} || {
+  echo 'failed'
 }
diff --git a/lib/bin/makedb-sqlite b/lib/bin/makedb-sqlite
--- a/lib/bin/makedb-sqlite
+++ b/lib/bin/makedb-sqlite
@@ -3,8 +3,11 @@ DIR=$(dirname "$BASH_SOURCE")
 . "$DIR/../bash/functions"
 echo -n 'working...'
 {
-  # TODO appdir
-  DBDIR="$DIR/../db"
+  [[ $# -ge 1 ]]
+} && {
+  INDIR="$(pwd)"
+} && {
+  DBDIR="$1"
   mkdir -p "$DBDIR" && cd "$DBDIR"
 } && {
   if [[ -f database.db ]]; then
@@ -13,16 +16,18 @@ echo -n 'working...'
   fi
 } && {
   sqlite3 database.db <<SQL
-.read ../src/sql/sqlite/schema.sql
+.read $INDIR/schema.sql
 SQL
 } && {
   if [[ -f ../src/sql/sqlite/data.sql ]]; then
     sqlite3 database.db <<SQL
-.read ../src/sql/sqlite/data.sql
+.read $INDIR/data.sql
 SQL
   fi
 } && {
   chmod -R a+w .
 } && {
   echo 'done'
+} || {
+  echo 'failed'
 }
